### ISSUE TITLE
Physicalモデルの作成

### ISSUE THREAD

**Issue by taniyu** [taniyu/weigery#13]
ユーザの身体情報を格納するphysicalモデルを作成する．
モデルのカラムについては， [wiki](/taniyu/weigery/wiki/model) 参照すること．
また，UserとPhysicalの関連は1対多である．

**Comment by taniyu** [comment]
同じissueがすでに存在するため削除

**Comment by MaxMEllon** [comment]
少し待っても無かったので自分が作ってしまいました．申し訳ございません．
