### ISSUE TITLE
本番環境でphysicals/indexが閲覧できない

### ISSUE THREAD

**Issue by 8398a7** [taniyu/weigery#32]
https://github.com/taniyu/weigery/commit/c76d829f9820cc1dee977a73425e34299e5d7c68#diff-21497849d8f00507c9c8dcaf6288b136R2

修正をお願いします．

**Comment by MaxMEllon** [comment]
issue #45 で routeが変わったので 要確認 :disappointed:

**Comment by 8398a7** [comment]
refs 9bfc66b8ce8fed3ceca97df52f43ab34ffd806f1
