### ISSUE TITLE
physical/indexに全てのユーザのデータが表示される

### ISSUE THREAD

**Issue by 8398a7** [taniyu/weigery#45]
とりあえずここに表示されるのは自分のデータだけでは．
グループ権限とかで今後グループが一緒の人を表示する欄とかはできると思うけど．

**Comment by MaxMEllon** [comment]
indexにuserのidを渡す必要があるのでルーティングも変更します

**Comment by 8398a7** [comment]
should check the test

**Comment by MaxMEllon** [comment]
testコード修正します
